apiVersion: externsions/v1beta1
kind: Pod
metadata:
  name: busybox
spec:
  template:
    spec:
      containers:
      - name: busybox
      image: busybox
      args:
      - sleep
      - "999"
      securityContext:
        privileged: true
