apiVersion: v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
      - image: my-image
        name: my-app
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          runAsUser: 0
